<a href="https://colab.research.google.com/github/SPraveeen/pandas_lectures/blob/main/Pandas_Solve" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])

In [ ]:
(x >= -5) & (x <= 15)

array([ True,  True, False, False,  True,  True, False,  True, False])

In [ ]:
x[(x >= -5) & (x <= 15)]

array([-5,  9, -3,  5, 10])

In [ ]:
x[(x >= -5) & (x <= 15)] *= -1

In [ ]:
x

array([  5,  -9,  20,  25,   3,  -5,  16, -10,  -8])

In [ ]:
n = 5
n *= 2
print(n)

In [ ]:
a = np.arange(2, 10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[3:7] *= - 1

In [ ]:
a

array([ 2,  3,  4, -5, -6, -7, -8,  9])

In [ ]:

!gdown 1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd

Downloading...
From: https://drive.google.com/uc?id=1s2TkjSpzNc4SyxqRrQleZyDIHlc7bxnd
To: /content/movies.csv
100% 112k/112k [00:00<00:00, 61.9MB/s]


In [ ]:
import pandas as pd

In [ ]:
movies = pd.read_csv('movies.csv', index_col=0)

In [ ]:
movies.head()

id     budget  popularity     revenue  \
0  43597  237000000         150  2787965087   
1  43598  300000000         139   961000000   
2  43599  245000000         107   880674609   
3  43600  250000000         112  1084939099   
5  43602  258000000         115   890871626   

                                      title  vote_average  vote_count  \
0                                    Avatar           7.2       11800   
1  Pirates of the Caribbean: At World's End           6.9        4500   
2                                   Spectre           6.3        4466   
3                     The Dark Knight Rises           7.6        9106   
5                              Spider-Man 3           5.9        3576   

   director_id  year month       day  
0         4762  2009   Dec  Thursday  
1         4763  2007   May  Saturday  
2         4764  2015   Oct    Monday  
3         4765  2012   Jul    Monday  
5         4767  2007   May   Tuesday

In [ ]:
movies['month'].unique()

array(['Dec', 'May', 'Oct', 'Jul', 'Mar', 'Jun', 'Nov', 'Apr', 'Feb',
       'Aug', 'Sep', 'Jan'], dtype=object)

In [ ]:
movies['director_id'].unique()

array([4762, 4763, 4764, 4765, 4767, 4771, 4772, 4773, 4774, 4775, 4776,
       4777, 4779, 4780, 4782, 4785, 4786, 4788, 4791, 4793, 4794, 4797,
       4798, 4799, 4802, 4803, 4804, 4805, 4808, 4809, 4810, 4811, 4812,
       4813, 4814, 4829, 4831, 4832, 4833, 4838, 4839, 4842, 4845, 4846,
       4847, 4849, 4854, 4857, 4858, 4859, 4863, 4865, 4866, 4867, 4868,
       4872, 4873, 4874, 4876, 4880, 4881, 4885, 4886, 4888, 4889, 4890,
       4892, 4893, 4894, 4900, 4904, 4909, 4913, 4915, 4917, 4918, 4921,
       4923, 4924, 4925, 4926, 4927, 4930, 4935, 4936, 4945, 4947, 4948,
       4949, 4955, 4958, 4960, 4964, 4965, 4967, 4974, 4978, 4989, 4991,
       4993, 4995, 4998, 5002, 5005, 5008, 5009, 5014, 5017, 5024, 5031,
       5033, 5034, 5035, 5037, 5039, 5047, 5053, 5056, 5059, 5061, 5067,
       5082, 5087, 5088, 5093, 5096, 5097, 5101, 5105, 5111, 5113, 5115,
       5116, 5123, 5125, 5130, 5132, 5135, 5140, 5147, 5148, 5152, 5157,
       5162, 5179, 5182, 5191, 5193, 5195, 5196, 52

In [ ]:
movies.unique()

AttributeError: ignored

In [ ]:
movies['month'].nunique()

12

In [ ]:
movies.nunique()

id              1465
budget           201
popularity       128
revenue         1267
title           1465
vote_average      51
vote_count      1019
director_id      199
year              41
month             12
day                7
dtype: int64

In [ ]:
movies['month']

0       Dec
1       May
2       Oct
3       Jul
5       May
       ... 
4736    May
4743    Sep
4748    Aug
4749    Jul
4768    Sep
Name: month, Length: 1465, dtype: object

In [ ]:
# array -> 1D
# ARRAY -> 2D

In [ ]:
arr = 2 * np.arange(0,2,0.5)
arr

array([0., 1., 2., 3.])

In [ ]:
if arr <= 0.6:
    print("condition satisfies")
else:
    print("condition doesn't satisfy")

ValueError: ignored

In [ ]:
if np.any(arr <= 0.6):
    print("condition satisfies")
else:
    print("condition doesn't satisfy")

condition satisfies


In [ ]:
arr <= 0.6

array([ True, False, False, False])

In [ ]:
np.any(arr <= 0.6)

True

In [ ]:
np.all(arr <= 0.6)

False

In [ ]:
pip install gdown==2.3.1

  Preparing metadata (setup.py) ... done
  Created wheel for gdown: filename=gdown-2.3.1-py3-none-any.whl size=3100 sha256=00037f25e3f96ccfc957df232de1b47d9d8e3ad26e029689aab9c29241126d1c
  Stored in directory: /root/.cache/pip/wheels/1c/06/57/fb29980fa37fd5c4526b8f4c2f338f14a14833ea060d86aed7
Successfully built gdown
  Attempting uninstall: gdown
    Found existing installation: gdown 4.6.6
    Uninstalling gdown-4.6.6:
      Successfully uninstalled gdown-4.6.6


In [ ]:
!wget https://www.dropbox.com/s/i85qjzm0cjh3p4z/UberData.csv

--2023-12-28 02:21:05--  https://www.dropbox.com/s/i85qjzm0cjh3p4z/UberData.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.80.18, 2620:100:601f:18::a27d:912
Connecting to www.dropbox.com (www.dropbox.com)|162.125.80.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/i85qjzm0cjh3p4z/UberData.csv [following]
--2023-12-28 02:21:06--  https://www.dropbox.com/s/raw/i85qjzm0cjh3p4z/UberData.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc621b03b5ec38d21a05d6149f86.dl.dropboxusercontent.com/cd/0/inline/CKM8KOUO6-fgf_WtNAwOiOUDT0UxmZtolQJKRMOGSroWf72uvnZ2ky015748lPwcVaNzMJsr6yMYe-wS4XhMvQ70FbnBNjfaDTE1r3Qg_Y6pxe1J6dZAC84bffnPzKGArs-vxmIJ7dBUdagCWusiyUjv/file# [following]
--2023-12-28 02:21:07--  https://uc621b03b5ec38d21a05d6149f86.dl.dropboxusercontent.com/cd/0/inline/CKM8KOUO6-fgf_WtNAwOiOUDT0UxmZtolQJKRMOGSroWf72uvnZ2ky015748lPwcVaNzMJsr6yMYe-wS4XhMvQ70FbnBNjfaDTE1

In [ ]:
# pd.read_csv('UberData.csv')
# pd.read_excel('mobilesales.xlsx')

In [ ]:
# pd.read_table('https://meta.wikimedia.org/wiki/List_of_Wikipedias_by_country')

In [ ]:
!wget https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg

--2023-12-28 02:25:06--  https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg
Resolving hips.hearstapps.com (hips.hearstapps.com)... 151.101.0.155, 151.101.64.155, 151.101.128.155, ...
Connecting to hips.hearstapps.com (hips.hearstapps.com)|151.101.0.155|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 229955 (225K) [image/jpeg]
Saving to: ‘dog-puppy-on-garden-royalty-free-image-1586966191.jpg’

dog-puppy-on-garden 100%[===================>] 224.57K  --.-KB/s    in 0.03s   

2023-12-28 02:25:06 (6.96 MB/s) - ‘dog-puppy-on-garden-royalty-free-image-1586966191.jpg’ saved [229955/229955]



In [ ]:
A = [[1,2,3],
     [4,5,6],
     [7,8,9]]



In [ ]:
nr = len(A)
nc = len(A[0])

In [ ]:
total = 0
for i in range(nr):
    for j in range(nc):
        if i == j:
            total += A[i][j]


print(total)

15


In [ ]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1])

1.0


In [ ]:
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])
print((p + q)[1][1])

21


In [ ]:
p

array([[ 0],
       [10],
       [20]])

In [ ]:
q

array([10, 11, 12])

In [ ]:
p+q

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
(p+q)[1]

array([20, 21, 22])

In [ ]:
(p+q)[1][1]

21

In [ ]:
A = np.arange(1, 10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A = A.T
A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
A[:, ::-1]

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [ ]:
movies.head()

id     budget  popularity     revenue  \
0  43597  237000000         150  2787965087   
1  43598  300000000         139   961000000   
2  43599  245000000         107   880674609   
3  43600  250000000         112  1084939099   
5  43602  258000000         115   890871626   

                                      title  vote_average  vote_count  \
0                                    Avatar           7.2       11800   
1  Pirates of the Caribbean: At World's End           6.9        4500   
2                                   Spectre           6.3        4466   
3                     The Dark Knight Rises           7.6        9106   
5                              Spider-Man 3           5.9        3576   

   director_id  year month       day  
0         4762  2009   Dec  Thursday  
1         4763  2007   May  Saturday  
2         4764  2015   Oct    Monday  
3         4765  2012   Jul    Monday  
5         4767  2007   May   Tuesday

In [ ]:
movies['title'].str.split().map(len)

0       1
1       7
2       1
3       4
5       2
       ..
4736    3
4743    1
4748    1
4749    1
4768    2
Name: title, Length: 1465, dtype: int64

In [ ]:
data = {
    'cust_id': [101, 102, 103, 104],
    'name': ['rick', 'morty', 'pickle', 'jerry']
}

customer = pd.DataFrame(data)

In [ ]:
data = {
    'order_id': ['OR1', 'OR3', 'OR23', 'OR42'],
    'cust_id': [102, 105, 101, 102],
    'amount': [1200, 650, 120, 989]
}

orders = pd.DataFrame(data)

In [ ]:
customer

cust_id    name
0      101    rick
1      102   morty
2      103  pickle
3      104   jerry

In [ ]:
orders

order_id  cust_id  amount
0      OR1      102    1200
1      OR3      105     650
2     OR23      101     120
3     OR42      102     989

In [ ]:
a = np.arange(5)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape

(5,)

In [ ]:
a.size

5

In [ ]:
a.sum()

10

In [ ]:
merged_df = customer.merge(orders, on='cust_id', how='left')

In [ ]:
merged_df

cust_id    name order_id  amount
0      101    rick     OR23   120.0
1      102   morty      OR1  1200.0
2      102   morty     OR42   989.0
3      103  pickle      NaN     NaN
4      104   jerry      NaN     NaN

In [ ]:
merged_df['name']=='morty'

0    False
1     True
2     True
3    False
4    False
Name: name, dtype: bool

In [ ]:
merged_df[merged_df['name']=='morty']

cust_id   name order_id  amount
1      102  morty      OR1  1200.0
2      102  morty     OR42   989.0